### ISSUE TITLE
cPanel Import disk quota issue

### ISSUE THREAD

**Issue by MACscr** [apisnetworks/apnscp#19]
Plenty of space on server, quota set on plan and statically on import is enough for account, yet get the following error about disk quota and then the import appears to stall out:

```INFO    : Created user lori, (old/new uid: 32079/21510)
ERROR   : rsync: rsync: chown "/home/virtual/site26/fst/home/lori/Mail/.Junk/new/.1570713143.M358472P32140.cp2.cloud.oldserver.com,S=6011048,W=6089153.a4sthP" failed: Disk quota exceeded (122)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

ERROR   : rsync: chown "/home/virtual/site26/fst/home/lori/Mail/.Junk/new/.1570713143.M358472P32140.cp2.cloud.oldserver.com,S=6011048,W=6089153.a4sthP" failed: Disk quota exceeded (122)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

INFO    : Created user rcushing, (old/new uid: 32079/21511)
INFO    : Created user aperry, (old/new uid: 32079/21512)
INFO    : Created user trazo, (old/new uid: 32079/21513)
WARNING : passwd missing in .boxtrapper, skipping```

**Comment by msaladna** [comment]
Quotas are read from `homedir/.cpanel/email_accounts.json`, specifically accounts.USERNAME.diskquota from the json field. It may be possible that either cPanel was not fully enforcing the quota for that user because everything is merged into a single UID and thus unenforceable on the kernel level. Verify that the quota for user "lori" matches the quota defined in the email_accounts.json.

```bash
quota -uv "$(cpcmd -d site26 user_get_uid_from_user_lori)"
```

quota field (in KB) should match up with the email_accounts.json quota field (in B).
