### ISSUE TITLE
Webmail logins as email addresses 

### ISSUE THREAD

**Issue by plattnat** [apisnetworks/apnscp#46]
Rather than have users login with username@domainname.ext have them login with emailaddress@domainname.ext. 

More inline with other platforms like, pleat, cPanel, office 365. Less confusion for users

**Comment by msaladna** [comment]
This isn't a possibility unless we move every user on an account to a single UID setup like cPanel, which introduces significant security concerns. Users are distinct system users each with their own UID in the system, likewise enforced by traditional discretionary access controls in the kernel. Authentication happens in PAM to provide a barrier between service and authentication. This requires logging in using the username@domain scheme as with su, FTP, and SSH.

At best we could shim some translation middleware to resolve the UID to a user. In this situation NSS isn't setup to translate the UID to the virtual account, so that would require additional rework.

One important thing to remember is that because the login notation is user@domain (or user#domain) it's coincidental that may also be their email address. You could provide clients with the login form user#domain instead of user@domain to break that mental association.

**Comment by msaladna** [comment]
Moved to [feedback.apiscp.com#39](https://feedback.apiscp.com/posts/39/webmail-logins-as-email-addresses)
